Models/Countries.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace CovidUpdate1.Models
{
    public class Idata
    {
    

        [DataMember]
        public string location { get; set; }
        
        [DataMember]
        public string data { get; set; }

    }
}

Models/Covid.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CovidUpdate1.Models
{
    public class Covid
    {
        public List<Idata> data { get; set; }
    }
}

Controllers/HomeController.cs
using CovidUpdate1.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CovidUpdate1.Controllers
{
    [DataContract]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            List<Idata> countries = null;
            var url = "https://www.trackcorona.live/api/travel";
            var syncClient = new WebClient();
            var data = syncClient.DownloadString(url);
            DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(Covid));
            using (var m = new MemoryStream(Encoding.Unicode.GetBytes(data)))
            {
                var covidUpdate1 = (Covid)serializer.ReadObject(m);
                countries = covidUpdate1.data;

            }




            return View(countries.ToList());
        }

      
    
    public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/TravelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CovidUpdate1.Controllers
{
    public class TravelController : Controller
    {
        // GET: Travel
        WebApiEntities db = new WebApiEntities();
        public ActionResult Index(string searching)
        {
            var travels = from t in db.Travels
                          select t;
            if (!String.IsNullOrEmpty(searching))
            {
                travels = travels.Where(t => t.Location.Contains(searching));
            }
            
            return View(travels.ToList());
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model IEnumerable<CovidUpdate1.Models.Idata>

@{
    ViewBag.Title = "Index";

    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div align="center">

    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for location..">

</div>


<table id="myTable" align="center">
    <tr class="header">

        <th>
            @Html.DisplayNameFor(model => model.location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.data)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr class="Search">
            <td>
                @Html.DisplayFor(modelItem => item.location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.data)
            </td>

        </tr>
    }

</table>
<script>
    function myFunction() {
        // Declare variables
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>


    <script src="@Url.Content("~/Scripts/jquery-3.1.1.min.js")"></script>

    <title>Choropleth Map</title>
    <link rel="stylesheet" href="~/Content/styles.css">
    <script src="https://unpkg.com/d3@5.6.0/dist/d3.min.js"></script>
    <script src="https://unpkg.com/topojson@3.0.2/dist/topojson.min.js"></script>



    @RenderSection("scripts", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Content/styles.css")
    @Scripts.Render("~/Scripts/bundle.js")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Covid 19 - Travel Ban Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    
    <h4 class="text-center">Hover over the map to see data or type in search bar to see travel bans</h4>
     <br/>
    <div style="text-align:center;">
        <svg preserveAspectRatio="xMidYMin" id="svgMain" width="960" height="500"></svg>
    </div>

    <script src="~/Scripts/bundle.js"></script>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

Views/Shared/_Layoutmap.cshtml
<!DOCTYPE html>

<html>
<head>

    <title>Choropleth Map</title>
    <link rel="stylesheet" href="~/Content/styles.css">
    <script src="https://unpkg.com/d3@5.6.0/dist/d3.min.js"></script>
    <script src="https://unpkg.com/topojson@3.0.2/dist/topojson.min.js"></script>

    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <div style="text-align:left;">
        <svg preserveAspectRatio="xMidYMin" id="svgMain" width="960" height="500"></svg>
    </div>

    <script src="~/Scripts/bundle.js"></script>


    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Travel/Index.cshtml
@model IEnumerable<CovidUpdate1.Travel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "Travel", FormMethod.Get))
{
@Html.TextBox("searching")
<input type="submit" value="submit"/>
}

<table>

    <tr>
        <th>
          location
        </th>
        <th>
           data
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            </tr>
    }

    </table>